# Generated by Django 5.0.7 on 2025-03-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='year',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='brand',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='price',
            new_name='precio',
        ),
    ]
